import streamlit as st
import pandas as pd
import os
from cleanData import clean_and_store

st.set_page_config(page_title="Emlic", layout="wide")

# Initialize Session State to track app progress
if 'processed' not in st.session_state: st.session_state.processed = False
if 'current_file' not in st.session_state: st.session_state.current_file = None

# Custom styling for a clean, professional interface
st.markdown("""
    <style>
    .block-container { padding-top: 4rem; padding-left: 6rem; padding-right: 6rem; }
    .stButton>button { border-radius: 4px; height: 3em; }
    h1 { font-weight: 400; color: #1f2937; }
    </style>
    """, unsafe_allow_html=True)

# Header Section
head_col1, head_col2 = st.columns([5, 1])
with head_col1:
    st.title("Emlic: Email List Cleaner")
    st.write("Professional utility for dynamic data normalization.")

with head_col2:
    # Reset button clears flags to hide results without deleting local data
    if st.button("Reset Workspace", type="secondary"):
        st.session_state.processed = False
        st.session_state.current_file = None
        st.rerun()

st.divider()

# Configuration Settings (LinkedIn removed)
st.subheader("Workflow Settings")
c1, c2, c3 = st.columns(3)
with c1: do_dedup = st.checkbox("Merge Duplicates", value=True)
with c2: do_timezone = st.checkbox("Calculate Timezones", value=False)
with c3: do_report = st.checkbox("SQL Database Entry", value=True)

st.markdown("<br>", unsafe_allow_html=True)

# Document Upload Management
u_col1, u_col2, u_col3 = st.columns([1, 2, 1])

with u_col2:
    uploaded_file = st.file_uploader("Upload CSV Lead List", type="csv")
    
    if uploaded_file:
        # Capture the actual filename to ensure we process the latest upload
        file_path = os.path.join("data-raw", uploaded_file.name)
        
        # Save file to disk and reset display if it's a new document
        if st.session_state.current_file != file_path:
            os.makedirs('data-raw', exist_ok=True)
            with open(file_path, "wb") as f:
                f.write(uploaded_file.getbuffer())
            st.session_state.current_file = file_path
            st.session_state.processed = False 
        
        st.info(f"Active File: {uploaded_file.name}")
        
        if st.button("Run Workflow", type="primary"):
            with st.spinner('Executing tasks...'):
                # Call backend without the LinkedIn argument
                result = clean_and_store(file_path, do_dedup, do_timezone, do_report)
            
            if result == "Success":
                st.session_state.processed = True
            else:
                st.error(result)

# Results Section
if st.session_state.processed:
    st.markdown("<br><hr><br>", unsafe_allow_html=True)
    # Load the fresh output generated by cleanData.py
    df_final = pd.read_csv("data-cleaned/crm_upload_ready.csv")

    m1, m2, m3, m4 = st.columns(4)
    m1.metric("Leads Identified", len(df_final))
    m2.metric("Verified Emails", len(df_final[df_final['Email_Status'] == 'Valid']))
    m3.metric("Database Status", "Synchronized")
    
    with m4:
        # Provide the processed file for direct download
        with open("data-cleaned/crm_upload_ready.csv", "rb") as file:
            st.download_button("Download Export", data=file, file_name="Processed_Leads.csv")

    st.subheader("Data Intelligence Preview")
    st.dataframe(df_final, use_container_width=True, height=400)